<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Robot Framework syntax highlighting for output files.</string>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>name</key>
	<string>Robot framework output</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(FAIL)\b</string>
			<key>name</key>
			<string>invalid.illegal</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(PASS)\b</string>
			<key>name</key>
			<string>string.robot.header</string>
		</dict>
		<dict>
			<key>match</key>
			<string>==</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(Output:|Log:|Report:)</string>
			<key>name</key>
			<string>constant.numeric.robot</string>
		</dict>
    <dict>
      <key>begin</key>
      <string>Test execution is complete and all tests passed</string>
      <key>end</key>
      <string>$</string>
      <key>name</key>
      <string>string.robot.header</string>
    </dict>
    <dict>
      <key>begin</key>
      <string>Test execution is complete, but there are test failures</string>
      <key>end</key>
      <string>$</string>
      <key>name</key>
      <string>keyword</string>
    </dict>
  </array>
	<key>scopeName</key>
	<string>text.robot</string>
	<key>uuid</key>
	<string>8728e0fe-14c6-4374-acde-da1857d0a378</string>
</dict>
</plist>
